# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/keymaster/gatekeeper

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/keymaster/gatekeeper

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/keymaster/gatekeeper/CMakeFiles /home/keymaster/gatekeeper/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/keymaster/gatekeeper/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gatekeeper

# Build rule for target.
gatekeeper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gatekeeper
.PHONY : gatekeeper

# fast build rule for target.
gatekeeper/fast:
	$(MAKE) -f CMakeFiles/gatekeeper.dir/build.make CMakeFiles/gatekeeper.dir/build
.PHONY : gatekeeper/fast

src/Event.o: src/Event.cpp.o
.PHONY : src/Event.o

# target to build an object file
src/Event.cpp.o:
	$(MAKE) -f CMakeFiles/gatekeeper.dir/build.make CMakeFiles/gatekeeper.dir/src/Event.cpp.o
.PHONY : src/Event.cpp.o

src/Event.i: src/Event.cpp.i
.PHONY : src/Event.i

# target to preprocess a source file
src/Event.cpp.i:
	$(MAKE) -f CMakeFiles/gatekeeper.dir/build.make CMakeFiles/gatekeeper.dir/src/Event.cpp.i
.PHONY : src/Event.cpp.i

src/Event.s: src/Event.cpp.s
.PHONY : src/Event.s

# target to generate assembly for a file
src/Event.cpp.s:
	$(MAKE) -f CMakeFiles/gatekeeper.dir/build.make CMakeFiles/gatekeeper.dir/src/Event.cpp.s
.PHONY : src/Event.cpp.s

src/Timer.o: src/Timer.cpp.o
.PHONY : src/Timer.o

# target to build an object file
src/Timer.cpp.o:
	$(MAKE) -f CMakeFiles/gatekeeper.dir/build.make CMakeFiles/gatekeeper.dir/src/Timer.cpp.o
.PHONY : src/Timer.cpp.o

src/Timer.i: src/Timer.cpp.i
.PHONY : src/Timer.i

# target to preprocess a source file
src/Timer.cpp.i:
	$(MAKE) -f CMakeFiles/gatekeeper.dir/build.make CMakeFiles/gatekeeper.dir/src/Timer.cpp.i
.PHONY : src/Timer.cpp.i

src/Timer.s: src/Timer.cpp.s
.PHONY : src/Timer.s

# target to generate assembly for a file
src/Timer.cpp.s:
	$(MAKE) -f CMakeFiles/gatekeeper.dir/build.make CMakeFiles/gatekeeper.dir/src/Timer.cpp.s
.PHONY : src/Timer.cpp.s

src/database.o: src/database.cpp.o
.PHONY : src/database.o

# target to build an object file
src/database.cpp.o:
	$(MAKE) -f CMakeFiles/gatekeeper.dir/build.make CMakeFiles/gatekeeper.dir/src/database.cpp.o
.PHONY : src/database.cpp.o

src/database.i: src/database.cpp.i
.PHONY : src/database.i

# target to preprocess a source file
src/database.cpp.i:
	$(MAKE) -f CMakeFiles/gatekeeper.dir/build.make CMakeFiles/gatekeeper.dir/src/database.cpp.i
.PHONY : src/database.cpp.i

src/database.s: src/database.cpp.s
.PHONY : src/database.s

# target to generate assembly for a file
src/database.cpp.s:
	$(MAKE) -f CMakeFiles/gatekeeper.dir/build.make CMakeFiles/gatekeeper.dir/src/database.cpp.s
.PHONY : src/database.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/gatekeeper.dir/build.make CMakeFiles/gatekeeper.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/gatekeeper.dir/build.make CMakeFiles/gatekeeper.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/gatekeeper.dir/build.make CMakeFiles/gatekeeper.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/ts_util.o: src/ts_util.cpp.o
.PHONY : src/ts_util.o

# target to build an object file
src/ts_util.cpp.o:
	$(MAKE) -f CMakeFiles/gatekeeper.dir/build.make CMakeFiles/gatekeeper.dir/src/ts_util.cpp.o
.PHONY : src/ts_util.cpp.o

src/ts_util.i: src/ts_util.cpp.i
.PHONY : src/ts_util.i

# target to preprocess a source file
src/ts_util.cpp.i:
	$(MAKE) -f CMakeFiles/gatekeeper.dir/build.make CMakeFiles/gatekeeper.dir/src/ts_util.cpp.i
.PHONY : src/ts_util.cpp.i

src/ts_util.s: src/ts_util.cpp.s
.PHONY : src/ts_util.s

# target to generate assembly for a file
src/ts_util.cpp.s:
	$(MAKE) -f CMakeFiles/gatekeeper.dir/build.make CMakeFiles/gatekeeper.dir/src/ts_util.cpp.s
.PHONY : src/ts_util.cpp.s

src/webinterface.o: src/webinterface.cpp.o
.PHONY : src/webinterface.o

# target to build an object file
src/webinterface.cpp.o:
	$(MAKE) -f CMakeFiles/gatekeeper.dir/build.make CMakeFiles/gatekeeper.dir/src/webinterface.cpp.o
.PHONY : src/webinterface.cpp.o

src/webinterface.i: src/webinterface.cpp.i
.PHONY : src/webinterface.i

# target to preprocess a source file
src/webinterface.cpp.i:
	$(MAKE) -f CMakeFiles/gatekeeper.dir/build.make CMakeFiles/gatekeeper.dir/src/webinterface.cpp.i
.PHONY : src/webinterface.cpp.i

src/webinterface.s: src/webinterface.cpp.s
.PHONY : src/webinterface.s

# target to generate assembly for a file
src/webinterface.cpp.s:
	$(MAKE) -f CMakeFiles/gatekeeper.dir/build.make CMakeFiles/gatekeeper.dir/src/webinterface.cpp.s
.PHONY : src/webinterface.cpp.s

src/wiegand.o: src/wiegand.cpp.o
.PHONY : src/wiegand.o

# target to build an object file
src/wiegand.cpp.o:
	$(MAKE) -f CMakeFiles/gatekeeper.dir/build.make CMakeFiles/gatekeeper.dir/src/wiegand.cpp.o
.PHONY : src/wiegand.cpp.o

src/wiegand.i: src/wiegand.cpp.i
.PHONY : src/wiegand.i

# target to preprocess a source file
src/wiegand.cpp.i:
	$(MAKE) -f CMakeFiles/gatekeeper.dir/build.make CMakeFiles/gatekeeper.dir/src/wiegand.cpp.i
.PHONY : src/wiegand.cpp.i

src/wiegand.s: src/wiegand.cpp.s
.PHONY : src/wiegand.s

# target to generate assembly for a file
src/wiegand.cpp.s:
	$(MAKE) -f CMakeFiles/gatekeeper.dir/build.make CMakeFiles/gatekeeper.dir/src/wiegand.cpp.s
.PHONY : src/wiegand.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... gatekeeper"
	@echo "... rebuild_cache"
	@echo "... src/Event.o"
	@echo "... src/Event.i"
	@echo "... src/Event.s"
	@echo "... src/Timer.o"
	@echo "... src/Timer.i"
	@echo "... src/Timer.s"
	@echo "... src/database.o"
	@echo "... src/database.i"
	@echo "... src/database.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/ts_util.o"
	@echo "... src/ts_util.i"
	@echo "... src/ts_util.s"
	@echo "... src/webinterface.o"
	@echo "... src/webinterface.i"
	@echo "... src/webinterface.s"
	@echo "... src/wiegand.o"
	@echo "... src/wiegand.i"
	@echo "... src/wiegand.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

